name: K-Deploy Action Example

on: workflow_dispatch

jobs:
  aks-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: '1.17.1'
          kustomize: '3.7.0'

      - name: K-Deploy Action
        uses: ./
        with:
          kubeconfig: .kubeconfig
          namespace: 'default'
          resources: example/deployment.yml