name: K-Deploy Action Example

on: workflow_dispatch

jobs:
  aks-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v2.0

      - name: K-Deploy Action
        uses: ./
        with:
          kubeconfig: .kubeconfig
          manifest: example/deploy/base/deployment.yml
          kustomize: false
          overlay: 'example/deploy/overlays/non-prod'