name: K-Deploy Action Example

on: workflow_dispatch

jobs:
  aks-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: K-Deploy Action
        uses: ./
        with:
          kubeconfig: .kubeconfig
          namespace: 'default'
          resources: example/deployment.yml