name: 'Kubernetes Deployment'
description: 'A GitHub Action to Deploy Apps to any Kubernetes Environment'
author: Tanmoy Sen Gupta <tanmoysps@gmail.com>
inputs:
  kubeconfig:
    description: 'Path to Kubeconfig'
    required: true
  namespace:
    description: 'Kubernetes Namespace'
    required: true
    default: 'default'
  resources:
    description: 'Path to resources Files'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: purple
