name: 'Kubernetes Deployment'
description: 'A GitHub Action to Deploy Apps to any Kubernetes Environment'
author: Tanmoy Sen Gupta <tanmoysps@gmail.com>
inputs:
  kubeconfig:
    description: 'Path to Kubeconfig'
    required: true
  namespace:
    description: 'Kubernetes Namespace'
    required: true
    default: 'default'
  manifest:
    description: 'Path to manifest Files'
    required: false
  kustomize:
    description: 'Boolean. If Kustomization is required'
    required: true
    default: false
  overlay:
    description: 'Path to overlay for kustomization'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: purple
