apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./cpu_count.yml

patchesStrategicMerge:
  - ./deployment.yml