apiVersion: apps/v1
kind: Deployment
metadata:
  name: logsmith
  labels:
    app: logsmith
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logsmith
  template:
    metadata:
      labels:
        app: logsmith
        role: leader
        tier: backend
    spec:
      containers:
      - name: logsmith
        image: "ghcr.io/tanmoysg/logsmith-monitor:v0.1.0"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080