name: K-Deploy Action Example

on: [push]

jobs:
  aks-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          kubeconfig: aks.kubeconfig
          deployments: example/deployment.yml