name: Feedback

on:
  issues:
    types: [labeled]

jobs:
  thanks-for-the-feedback:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'feedback' }}

    steps:
      - name: Thank You!
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :bow: Thank You for your feedback @${{github.actor}}